/*CRIANDO A TABELA PERSONAGEM*/
CREATE TABLE PERSONAGEM (
ID NUMBER NOT NULL,
NOME VARCHAR2(100) NOT NULL,
MOEDA NUMBER NOT NULL,
VIDA NUMBER NOT NULL,
DEFESA NUMBER NOT NULL,
ATAQUE NUMBER NOT NULL,
AGILIDADE NUMBER NOT NULL,
NOME_ARMA VARCHAR2(100) NOT NULL,
NOME_ARMADURA VARCHAR2(100)NOT NULL,
NOME_RACA VARCHAR2(100) NOT NULL,
NOME_CLASSE VARCHAR2(100)NOT NULL,
CONSTRAINT PERSONAGEM_PK PRIMARY KEY(ID)
ENABLE
);

/*CRIANDO A TABELA RACA*/
CREATE TABLE RACA(
NOME VARCHAR2(100) NOT NULL,
VIDA NUMBER NOT NULL,
DEFESA NUMBER NOT NULL,
ATAQUE NUMBER NOT NULL,
AGILIDADE NUMBER NOT NULL,
CONSTRAINT RACA_PK PRIMARY KEY(NOME)
ENABLE
);

/*CRIANDO A TABELA CLASSE*/
CREATE TABLE CLASSE(
NOME VARCHAR2(100) NOT NULL,
VIDA NUMBER NOT NULL,
DEFESA NUMBER NOT NULL,
ATAQUE NUMBER NOT NULL,
AGILIDADE NUMBER NOT NULL,
CONSTRAINT CLASSE_PK PRIMARY KEY(NOME) 
ENABLE
);

/*CRIANDO A TABELA ARMA*/
CREATE TABLE ARMA(
NOME VARCHAR2(100) NOT NULL,
MATERIAL VARCHAR2(100) NOT NULL,
ATAQUE NUMBER NOT NULL,
CONSTRAINT ARMA_PK PRIMARY KEY(NOME)
ENABLE
);

/*CRIANDO A TABELA ARMADURA*/
CREATE TABLE ARMADURA(
NOME VARCHAR2(100) NOT NULL,
MATERIAL VARCHAR2(100) NOT NULL,
DEFESA NUMBER NOT NULL,
CONSTRAINT ARMADURA_PK PRIMARY KEY(NOME)
ENABLE
);


/*FOREIGN KEY NA TABELA PERSONAGEM*/
ALTER TABLE PERSONAGEM ADD CONSTRAINT FK_NOME_ARMA FOREIGN KEY(NOME_ARMA) REFERENCES ARMA(NOME);
ALTER TABLE PERSONAGEM ADD CONSTRAINT FK_NOME_ARMADURA FOREIGN KEY(NOME_ARMADURA) REFERENCES ARMADURA(NOME);
ALTER TABLE PERSONAGEM ADD CONSTRAINT FK_NOME_RACA FOREIGN KEY(NOME_RACA) REFERENCES RACA(NOME);
ALTER TABLE PERSONAGEM ADD CONSTRAINT FK_NOME_CLASSE FOREIGN KEY(NOME_CLASSE) REFERENCES CLASSE(NOME);







/*CRIANDO A TABELA MISSAO*/
CREATE TABLE MISSAO (
ID NUMBER NOT NULL,
NOME VARCHAR2(100) NOT NULL,
HISTORIA VARCHAR2(4000) NOT NULL,
CONSTRAINT MISSAO_PK PRIMARY KEY(ID)
ENABLE
);

/*CRIANDO A TABELA PERSONAGEM_MISSAO*/
CREATE TABLE PERSONAGEM_MISSAO (
ID NUMBER NOT NULL,
ID_PERSONAGEM NUMBER NOT NULL,
ID_MISSAO NUMBER NOT NULL,
CONCLUIDA VARCHAR2(1) NOT NULL,
CONSTRAINT PERSONAGEM_MISSAO_PK PRIMARY KEY(ID)
ENABLE
);

/*CRIANDO A TABELA FASE*/
CREATE TABLE FASE (
ID NUMBER NOT NULL,
NOME VARCHAR2(100) NOT NULL,
HISTORIA VARCHAR2(4000) NOT NULL,
ORDEM NUMBER NOT NULL,
OP1 NUMBER NOT NULL,
HistResultadoOP1 VARCHAR2(4000) NOT NULL,
OP2 NUMBER NOT NULL,
HistResultadoOP2 VARCHAR2(4000) NOT NULL,
ID_MISSAO NUMBER NOT NULL,
ID_OBJETIVO NUMBER NOT NULL,
CONSTRAINT FASE_PK PRIMARY KEY(ID)
ENABLE
);

/*CRIANDO A TABELA OBJEIVO*/
CREATE TABLE OBJETIVO (
ID NUMBER NOT NULL,
NOME VARCHAR2(100) NOT NULL,
MOEDA NUMBER NOT NULL,
FINAL VARCHAR2(1) NOT NULL,
NOME_ARMADURA VARCHAR2(100) NULL,
NOME_ARMA VARCHAR2(100) NULL,
CONSTRAINT OBJETIVO_PK PRIMARY KEY(ID)
ENABLE
);

/*FOREIGN KEY NA TABELA PERSONAGEM_MISSAO*/
ALTER TABLE PERSONAGEM_MISSAO ADD CONSTRAINT FK_ID_PERSONAGEM FOREIGN KEY(ID_PERSONAGEM) REFERENCES PERSONAGEM(ID);
ALTER TABLE PERSONAGEM_MISSAO ADD CONSTRAINT FK_ID_MISSAO FOREIGN KEY(ID_MISSAO) REFERENCES MISSAO(ID);

/*FOREIGN KEY NA TABELA FASE*/
ALTER TABLE FASE ADD CONSTRAINT FK_ID_MISSAO_FASE FOREIGN KEY(ID_MISSAO) REFERENCES MISSAO(ID);
ALTER TABLE FASE ADD CONSTRAINT FK_ID_OBJETIVO_FASE FOREIGN KEY(ID_OBJETIVO) REFERENCES OBJETIVO(ID);
ALTER TABLE FASE ADD CONSTRAINT FK_ID_FASE_OP1 FOREIGN KEY(OP1) REFERENCES FASE(ID);
ALTER TABLE FASE ADD CONSTRAINT FK_ID_FASE_OP2 FOREIGN KEY(OP2) REFERENCES FASE(ID);

/*FOREIGN KEY NA TABELA OBJETIVO*/
ALTER TABLE OBJETIVO ADD CONSTRAINT FK_NOME_ARMADURA_OBJ FOREIGN KEY(NOME_ARMADURA) REFERENCES ARMADURA(NOME);
ALTER TABLE OBJETIVO ADD CONSTRAINT FK_NOME_ARMA_OBJ FOREIGN KEY(NOME_ARMA) REFERENCES ARMA(NOME);


/*CRIANDO SEQUENCE DO COMPO ID_PERSONAGEM DA TABELA PERSONAGEM*/
CREATE SEQUENCE S_ID_PERSONAGEM INCREMENT BY 1 START WITH 1 MINVALUE 1;

/*CRIANDO SEQUENCE DO COMPO ID_MISSAO DA TABELA MISSAO*/
CREATE SEQUENCE S_ID_MISSAO INCREMENT BY 1 START WITH 1 MINVALUE 1;

/*CRIANDO SEQUENCE DO COMPO ID_MISSAO DA TABELA PERSONAGEM_MISSAO*/
CREATE SEQUENCE S_ID_PERSONAGEM_MISSAO INCREMENT BY 1 START WITH 1 MINVALUE 1;

/*CRIANDO SEQUENCE DO COMPO ID_MISSAO DA TABELA FASE*/
CREATE SEQUENCE S_ID_FASE INCREMENT BY 1 START WITH 1 MINVALUE 1;

/*CRIANDO SEQUENCE DO COMPO ID_MISSAO DA TABELA OBJETIVO*/
CREATE SEQUENCE S_ID_OBJETIVO INCREMENT BY 1 START WITH 1 MINVALUE 1;


INSERT INTO RACA (NOME, VIDA, DEFESA, ATAQUE, AGILIDADE) 
    VALUES ('HUMANO', 10, 20, 5, 5);
INSERT INTO RACA (NOME, VIDA, DEFESA, ATAQUE, AGILIDADE) 
    VALUES ('ELFO', 15, 5, 10, 10);
INSERT INTO RACA (NOME, VIDA, DEFESA, ATAQUE, AGILIDADE) 
    VALUES ('DEMI HUMANO', 20, 5, 20, 2);

INSERT INTO CLASSE (nome,vida,defesa,ataque,agilidade)
    VALUES ('LUTADOR', 10,15,15,15);
INSERT INTO CLASSE (nome,vida,defesa,ataque,agilidade)
    VALUES ('MERCENARIO', 20,10,10,15);
INSERT INTO CLASSE (nome,vida,defesa,ataque,agilidade)
    VALUES ('ATIRADOR', 10,10,20,20);    

INSERT INTO ARMA (NOME,MATERIAL,ATAQUE) 
    VALUES ('Cristal Sword','Cristais',5);
INSERT INTO ARMA (NOME,MATERIAL,ATAQUE) 
    VALUES ('Lança Do Vazio','Essencia do Vazio',3);
INSERT INTO ARMA (NOME,MATERIAL,ATAQUE) 
    VALUES ('Pistola Elfica','Aparelhos tecnologicos elficos',7);

INSERT INTO ARMADURA (NOME,MATERIAL, defesa) 
    VALUES ('Cristal','Cristais',5);
INSERT INTO ARMADURA (NOME,MATERIAL,DEFESA) 
    VALUES ('Esculdo Do Vazio','Essencia do Vazio',3);
INSERT INTO ARMADURA (NOME,MATERIAL,DEFESA) 
    VALUES ('Bracilete Elfica','Aparelhos tecnologicos elficos',7);
